package card

import "citadels-backend/logic/game/card/template"

func GenerateCards(color template.BuildingColor) []Building { return cardsByColor[color] }

var cardsByColor = map[template.BuildingColor][]Building{
	template.Yellow: {
		BuildingFromTemplate(template.Palace),
		BuildingFromTemplate(template.Palace),
		BuildingFromTemplate(template.Palace),
		BuildingFromTemplate(template.Palace),
		BuildingFromTemplate(template.Castle),
		BuildingFromTemplate(template.Castle),
		BuildingFromTemplate(template.Castle),
		BuildingFromTemplate(template.Mansion),
		BuildingFromTemplate(template.Mansion),
		BuildingFromTemplate(template.Mansion),
		BuildingFromTemplate(template.Mansion),
		BuildingFromTemplate(template.Mansion),
	},
	template.Green: {
		BuildingFromTemplate(template.Tavern),
		BuildingFromTemplate(template.Tavern),
		BuildingFromTemplate(template.Tavern),
		BuildingFromTemplate(template.Tavern),
		BuildingFromTemplate(template.Tavern),
		BuildingFromTemplate(template.Shop),
		BuildingFromTemplate(template.Shop),
		BuildingFromTemplate(template.Shop),
		BuildingFromTemplate(template.Port),
		BuildingFromTemplate(template.Port),
		BuildingFromTemplate(template.Port),
		BuildingFromTemplate(template.TownHall),
		BuildingFromTemplate(template.TownHall),
		BuildingFromTemplate(template.Harbor),
		BuildingFromTemplate(template.Harbor),
		BuildingFromTemplate(template.Harbor),
		BuildingFromTemplate(template.Market),
		BuildingFromTemplate(template.Market),
		BuildingFromTemplate(template.Market),
		BuildingFromTemplate(template.Market),
	},
	template.Red: {
		BuildingFromTemplate(template.Watchtower),
		BuildingFromTemplate(template.Watchtower),
		BuildingFromTemplate(template.Watchtower),
		BuildingFromTemplate(template.Prison),
		BuildingFromTemplate(template.Prison),
		BuildingFromTemplate(template.Prison),
		BuildingFromTemplate(template.Barracks),
		BuildingFromTemplate(template.Barracks),
		BuildingFromTemplate(template.Barracks),
		BuildingFromTemplate(template.Fortress),
		BuildingFromTemplate(template.Fortress),
	},
	template.Blue: {
		BuildingFromTemplate(template.Temple),
		BuildingFromTemplate(template.Temple),
		BuildingFromTemplate(template.Temple),
		BuildingFromTemplate(template.Church),
		BuildingFromTemplate(template.Church),
		BuildingFromTemplate(template.Church),
		BuildingFromTemplate(template.Monastery),
		BuildingFromTemplate(template.Monastery),
		BuildingFromTemplate(template.Monastery),
		BuildingFromTemplate(template.Cathedral),
		BuildingFromTemplate(template.Cathedral),
	},
	template.Purple: {
		BuildingFromTemplate(template.GreatWall),
		BuildingFromTemplate(template.Forge),
		BuildingFromTemplate(template.Capitol),
	},
}
